sudo: required
services:
  - docker

before_install:
  - docker build -t jmc574dude/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jmc574dude/docker-react npm run test
  
deploy:
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-us-west-1-218334699468"
  bucket_path: "frontend"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
